### ISSUE TITLE
callback may return a promise

### ISSUE THREAD

**Issue by jantimon** [lukewarlow/view-transitions-api-types#1]
the `callback` of `startViewTransition` may return a promise:

https://drafts.csswg.org/css-view-transitions/#additions-to-document-api

```ts
startViewTransition?: (updateCallback?: (() => void | Promise<void>)) => 
```

**Comment by lukewarlow** [comment]
My type matches the spec here right specifying a promise return?

**Comment by lukewarlow** [comment]
![Screenshot_20230910-180704.png](https://github.com/lukewarlow/view-transitions-api-types/assets/32498324/ac2f3535-78c5-4fe7-8590-a1b92a2bb40b)

Please correct me if I've misunderstood.

**Comment by lukewarlow** [comment]
Ah I've just spotted mine returns a promise but the spec says it is a promise itself.

Thanks for pointing that out. I'll correct this tomorrow and push out an update.

**Comment by lukewarlow** [comment]
Firstly apologies for the delay in getting back to this.

@jantimon sorry can I just double check is there actually an issue with my code. I re-read the spec an it appears it does in fact match my types. UpdateCallback is a callback that returns Promise<void> like my type does.

It also partly matches https://github.com/nuxt/nuxt/blob/ceab38770d5e80929518cfd5c71081756288bb55/packages/nuxt/src/app/plugins/view-transitions.client.ts#L5

Nuxt is also allowing a void return type for the callback which doesn't seem to actually match the spec?

**Comment by jantimon** [comment]
looks good to me 👍

you are right according to

https://developer.mozilla.org/en-US/docs/Web/API/ViewTransition

and

https://drafts.csswg.org/css-view-transitions/#callbackdef-updatecallback

the return type of updateCallback has to be a promise:

> Then, when the promise returned by updateCallback fulfills, the new state of the document is captured and the transition is initiated.

however the current implementation in chrome seems to allow `void` too

**Comment by lukewarlow** [comment]
I'm going to go ahead and close this for now as the types match the specification but feel free to open a new one in future if the spec updates.
